#+-------------------------------------------------------------------------------------------------+
#| Project makefile for the LED blink example.                                                     |
#|                                                                                                 |
#| Author: Joksan Alvarado.                                                                        |
#+-------------------------------------------------------------------------------------------------+

#Set the main target.
all: blink

#Configure contiki for out of tree compilation and include its main makefile.
CONTIKI = ../../contiki
TARGETDIRS += ../../platform
include $(CONTIKI)/Makefile.include
